name: Build packages

on: workflow_dispatch

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        sdk:
          - SNAPSHOT

    steps:
      - name: Maximize build space & Add Swap
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 16384 # 增加 16GB 的 Swap
          
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Clone specific package
        run: |
          mkdir -p packages_ci
          git clone --depth 1 https://github.com/QiuSimons/luci-app-daed.git packages_ci
          
      - name: Get node-empty
        run: |
          git clone https://github.com/sbwml/node-empty packages_ci

      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install clang llvm npm
          sudo npm install -g pnpm
          sudo npm install -g n
          sudo npm i taze -g
          sudo n stable
          latest_commit="$(curl -s https://api.github.com/repos/daeuniverse/daed/commits/main | jq -r '.sha' | cut -b 1-7)"
          latest_wing_commit="$(curl -s https://api.github.com/repos/daeuniverse/dae-wing/commits/main | jq -r '.sha' | cut -b 1-7)"
          latest_core_commit="$(curl -s https://api.github.com/repos/daeuniverse/dae/commits/main | jq -r '.sha' | cut -b 1-7)"
          timestamp=$(curl -s https://api.github.com/repos/daeuniverse/daed/commits/main | jq -r '.commit.author.date')
          formatted_timestamp=$(date --date="$timestamp" "+%Y-%m-%d")
          echo "version=$latest_commit-wing_$latest_wing_commit-core_$latest_core_commit" >> "$GITHUB_ENV"

      - name: Check Directory
        run: |
          echo "正在检查当前目录下的文件..."
          ls -F
          ls -R ${{ github.workspace }}/packages_ci
      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@go1.25
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEED_DIR: ${{ github.workspace }}/packages_ci
          PACKAGES: luci-app-daed
          NO_REFRESH_CHECK: true
          V: s

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/*/*.apk

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          name: daed_${{ env.version }}
          allowUpdates: true
          tag: daed_${{ env.version }}
          commit: main
          token: ${{secrets.GITHUB_TOKEN}}
          replacesArtifacts: true
          artifacts: "bin/packages/${{ matrix.arch }}/*/*.apk"
